/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner } from '../models/AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner';
import { HttpFile } from '../http/http';

export class AccountSupportedPlatforms200ResponseResult {
    'supportedPlatforms'?: Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "supportedPlatforms",
            "baseName": "supported_platforms",
            "type": "Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountSupportedPlatforms200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
