/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner } from '../models/AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner';
import { HttpFile } from '../http/http';

export class AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams {
    'required'?: Array<Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner>>;
    'additional'?: Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner>>",
            "format": ""
        },
        {
            "name": "additional",
            "baseName": "additional",
            "type": "Array<AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParamsRequiredInnerInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountSupportedPlatforms200ResponseResultSupportedPlatformsInnerParams.attributeTypeMap;
    }

    public constructor() {
    }
}
