/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountCartList200ResponseResultCartsInner } from '../models/AccountCartList200ResponseResultCartsInner';
import { HttpFile } from '../http/http';

export class AccountCartList200ResponseResult {
    'cartsCount'?: number;
    'carts'?: Array<AccountCartList200ResponseResultCartsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cartsCount",
            "baseName": "carts_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "carts",
            "baseName": "carts",
            "type": "Array<AccountCartList200ResponseResultCartsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountCartList200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
