/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BatchJobResultItem } from '../models/BatchJobResultItem';
import { HttpFile } from '../http/http';

export class BatchJobResult {
    'jobId'?: number;
    'jobName'?: string;
    'itemsProcessed'?: number;
    'itemsSucceed'?: number;
    'items'?: Array<BatchJobResultItem>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "jobName",
            "baseName": "job_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemsProcessed",
            "baseName": "items_processed",
            "type": "number",
            "format": ""
        },
        {
            "name": "itemsSucceed",
            "baseName": "items_succeed",
            "type": "number",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BatchJobResultItem>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BatchJobResult.attributeTypeMap;
    }

    public constructor() {
    }
}
