/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartShippingMethod } from '../models/CartShippingMethod';
import { Country } from '../models/Country';
import { HttpFile } from '../http/http';

export class CartShippingZone2 {
    'id'?: string;
    'name'?: string;
    'enabled'?: boolean;
    'countries'?: Array<Country>;
    'shippingMethods'?: Array<CartShippingMethod>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<Country>",
            "format": ""
        },
        {
            "name": "shippingMethods",
            "baseName": "shipping_methods",
            "type": "Array<CartShippingMethod>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartShippingZone2.attributeTypeMap;
    }

    public constructor() {
    }
}
