/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Carrier } from '../models/Carrier';
import { CartChannel } from '../models/CartChannel';
import { Currency } from '../models/Currency';
import { Info } from '../models/Info';
import { Language } from '../models/Language';
import { HttpFile } from '../http/http';

export class CartStoreInfo {
    'storeId'?: string;
    'name'?: string | null;
    'language'?: string | null;
    'storeLanguages'?: Array<Language>;
    'currency'?: Currency;
    'storeCurrencies'?: Array<Currency>;
    'timezone'?: string | null;
    'country'?: string | null;
    'rootCategoryId'?: string | null;
    'multiStoreUrl'?: string | null;
    'active'?: boolean | null;
    'weightUnit'?: string | null;
    'dimensionUnit'?: string | null;
    'pricesIncludeTax'?: boolean | null;
    'carrierInfo'?: Array<Carrier>;
    'storeOwnerInfo'?: Info | null;
    'defaultWarehouseId'?: string | null;
    'channels'?: Array<CartChannel>;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeLanguages",
            "baseName": "store_languages",
            "type": "Array<Language>",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency",
            "format": ""
        },
        {
            "name": "storeCurrencies",
            "baseName": "store_currencies",
            "type": "Array<Currency>",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "rootCategoryId",
            "baseName": "root_category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "multiStoreUrl",
            "baseName": "multi_store_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "dimensionUnit",
            "baseName": "dimension_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "pricesIncludeTax",
            "baseName": "prices_include_tax",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "carrierInfo",
            "baseName": "carrier_info",
            "type": "Array<Carrier>",
            "format": ""
        },
        {
            "name": "storeOwnerInfo",
            "baseName": "store_owner_info",
            "type": "Info",
            "format": ""
        },
        {
            "name": "defaultWarehouseId",
            "baseName": "default_warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<CartChannel>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartStoreInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
