/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartShippingMethodRate } from '../models/CartShippingMethodRate';
import { HttpFile } from '../http/http';

export class CartShippingMethod {
    'name'?: string | null;
    'handlingFee'?: string | null;
    'handlingEnabled'?: string | null;
    'handlingType'?: string | null;
    'defaultPrice'?: string | null;
    'defaultPriceType'?: string | null;
    'type'?: string | null;
    'enabled'?: string | null;
    'minOrderAmount'?: string | null;
    'rates'?: Array<CartShippingMethodRate>;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "handlingFee",
            "baseName": "handling_fee",
            "type": "string",
            "format": ""
        },
        {
            "name": "handlingEnabled",
            "baseName": "handling_enabled",
            "type": "string",
            "format": ""
        },
        {
            "name": "handlingType",
            "baseName": "handling_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultPrice",
            "baseName": "default_price",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultPriceType",
            "baseName": "default_price_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "string",
            "format": ""
        },
        {
            "name": "minOrderAmount",
            "baseName": "min_order_amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "rates",
            "baseName": "rates",
            "type": "Array<CartShippingMethodRate>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartShippingMethod.attributeTypeMap;
    }

    public constructor() {
    }
}
