/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountCartAddHybrisWebsitesInner } from '../models/AccountCartAddHybrisWebsitesInner';
import { HttpFile } from '../http/http';

export class CartCreate {
    /**
    * Store’s identifier which you can get from cart_list method
    */
    'cartId': CartCreateCartIdEnum;
    /**
    * A web address of a store that you would like to connect to API2Cart
    */
    'storeUrl'?: string;
    /**
    * This parameter allows to set up store with custom bridge url (also you must use store_root parameter if a bridge folder is not in the root folder of the store)
    */
    'bridgeUrl'?: string;
    /**
    * Absolute path to the store root directory (used with \"bridge_url\" parameter)
    */
    'storeRoot'?: string;
    /**
    * Set this parameter if bridge is already uploaded to store
    */
    'storeKey'?: string;
    /**
    * Shared secret
    */
    'sharedSecret'?: string;
    /**
    * Specify if api2cart should validate cart version
    */
    'validateVersion'?: boolean;
    /**
    * Enables or disables cart\'s verification
    */
    'verify'?: boolean;
    /**
    * DB tables prefix
    */
    'dbTablesPrefix'?: string;
    /**
    * This parameter allows you to set your custom user agent, which will be used in requests to the store. Please use it cautiously, as the store\'s firewall may block specific values.
    */
    'userAgent'?: string;
    /**
    * FTP connection host
    */
    'ftpHost'?: string;
    /**
    * FTP User
    */
    'ftpUser'?: string;
    /**
    * FTP Password
    */
    'ftpPassword'?: string;
    /**
    * FTP Port
    */
    'ftpPort'?: number;
    /**
    * FTP Store dir
    */
    'ftpStoreDir'?: string;
    /**
    * 3DCart API Key
    */
    'apiKey3dcart'?: string;
    /**
    * It\'s a BigCommerce account for which API is enabled
    */
    'adminAccount'?: string;
    /**
    * BigCommerce API URL
    */
    'apiPath'?: string;
    /**
    * Bigcommerce API Key
    */
    'apiKeyBigcommerce'?: string;
    /**
    * Client ID of the requesting app
    */
    'clientId'?: string;
    /**
    * Access token authorizing the app to access resources on behalf of a user
    */
    'accessToken'?: string;
    /**
    * API Path section unique to the store
    */
    'context'?: string;
    /**
    * Access token authorizing the app to access resources on behalf of a user
    */
    'accessToken'?: string;
    /**
    * Shopify API Key
    */
    'apiKeyShopify'?: string;
    /**
    * Shopify API Password
    */
    'apiPassword'?: string;
    /**
    * Access token authorizing the app to access resources on behalf of a user
    */
    'accessTokenShopify'?: string;
    /**
    * Neto API Key
    */
    'apiKey'?: string;
    /**
    * Neto User Name
    */
    'apiUsername'?: string;
    /**
    * Volusion API Password
    */
    'encryptedPassword'?: string;
    /**
    * It\'s a Volusion account for which API is enabled
    */
    'login'?: string;
    /**
    * It\'s a AspDotNetStorefront account for which API is available
    */
    'apiUserAdnsf'?: string;
    /**
    * AspDotNetStorefront API Password
    */
    'apiPass'?: string;
    /**
    * 3DCart Application Private Key
    */
    'privateKey'?: string;
    /**
    * 3DCart Token from Application
    */
    'appToken'?: string;
    /**
    * Etsy keystring
    */
    'etsyKeystring'?: string;
    /**
    * Etsy shared secret
    */
    'etsySharedSecret'?: string;
    /**
    * Secret token authorizing the app to access resources on behalf of a user
    */
    'tokenSecret'?: string;
    /**
    * Etsy Client Id
    */
    'etsyClientId'?: string;
    /**
    * Etsy Refresh token
    */
    'etsyRefreshToken'?: string;
    /**
    * Application ID (AppID).
    */
    'ebayClientId'?: string;
    /**
    * Shared Secret from eBay application
    */
    'ebayClientSecret'?: string;
    /**
    * The RuName value that eBay assigns to your application.
    */
    'ebayRuname'?: string;
    /**
    * Used to authenticate API requests.
    */
    'ebayAccessToken'?: string;
    /**
    * Used to renew the access token.
    */
    'ebayRefreshToken'?: string;
    /**
    * eBay environment
    */
    'ebayEnvironment'?: string;
    /**
    * eBay global ID
    */
    'ebaySiteId'?: number;
    /**
    * Demandware client id
    */
    'dwClientId'?: string;
    /**
    * Demandware api password
    */
    'dwApiPass'?: string;
    /**
    * Demandware user name
    */
    'demandwareUserName'?: string;
    /**
    * Demandware user password
    */
    'demandwareUserPassword'?: string;
    /**
    * Store Id
    */
    'storeId': string;
    /**
    * Seller Id
    */
    'sellerId'?: string;
    /**
    * 
    */
    'environment'?: string;
    /**
    * Omni Commerce Connector Client ID
    */
    'hybrisClientId'?: string;
    /**
    * Omni Commerce Connector Client Secret
    */
    'hybrisClientSecret'?: string;
    /**
    * User Name
    */
    'hybrisUsername'?: string;
    /**
    * User password
    */
    'hybrisPassword'?: string;
    /**
    * Websites to stores mapping data
    */
    'hybrisWebsites'?: Array<AccountCartAddHybrisWebsitesInner>;
    /**
    * Walmart client ID. For the region \'ca\' use Consumer ID
    */
    'walmartClientId'?: string;
    /**
    * Walmart client secret. For the region \'ca\' use Private Key
    */
    'walmartClientSecret'?: string;
    /**
    * Walmart environment
    */
    'walmartEnvironment'?: string;
    /**
    * Walmart WM_CONSUMER.CHANNEL.TYPE header
    */
    'walmartChannelType'?: string;
    /**
    * Walmart region
    */
    'walmartRegion'?: string;
    /**
    * LightSpeed api key
    */
    'lightspeedApiKey'?: string;
    /**
    * LightSpeed api secret
    */
    'lightspeedApiSecret'?: string;
    /**
    * Access token authorizing the app to access resources on behalf of a user
    */
    'shoplazzaAccessToken'?: string;
    /**
    * Shared secret
    */
    'shoplazzaSharedSecret'?: string;
    /**
    * Shopware access key
    */
    'shopwareAccessKey'?: string;
    /**
    * Shopware api key
    */
    'shopwareApiKey'?: string;
    /**
    * Shopware client secret access key
    */
    'shopwareApiSecret'?: string;
    /**
    * CommerceHQ api key
    */
    'commercehqApiKey'?: string;
    /**
    * CommerceHQ api password
    */
    'commercehqApiPassword'?: string;
    /**
    * 3DCart Private Key
    */
    '_3dcartPrivateKey'?: string;
    /**
    * 3DCart Token
    */
    '_3dcartAccessToken'?: string;
    /**
    * Woocommerce consumer key
    */
    'wcConsumerKey'?: string;
    /**
    * Woocommerce consumer secret
    */
    'wcConsumerSecret'?: string;
    /**
    * Magento Consumer Key
    */
    'magentoConsumerKey'?: string;
    /**
    * Magento Consumer Secret
    */
    'magentoConsumerSecret'?: string;
    /**
    * Magento Access Token
    */
    'magentoAccessToken'?: string;
    /**
    * Magento Token Secret
    */
    'magentoTokenSecret'?: string;
    /**
    * Prestashop webservice key
    */
    'prestashopWebserviceKey'?: string;
    /**
    * Wix App ID
    */
    'wixAppId': string;
    /**
    * Wix App Secret Key
    */
    'wixAppSecretKey': string;
    /**
    * Wix Instance ID
    */
    'wixInstanceId'?: string;
    /**
    * Wix refresh token
    */
    'wixRefreshToken'?: string;
    /**
    * Mercado Libre App ID
    */
    'mercadoLibreAppId'?: string;
    /**
    * Mercado Libre App Secret Key
    */
    'mercadoLibreAppSecretKey'?: string;
    /**
    * Mercado Libre Refresh Token
    */
    'mercadoLibreRefreshToken'?: string;
    /**
    * Zid Client ID
    */
    'zidClientId'?: number;
    /**
    * Zid Client Secret
    */
    'zidClientSecret'?: string;
    /**
    * Zid Access Token
    */
    'zidAccessToken'?: string;
    /**
    * Zid Authorization
    */
    'zidAuthorization'?: string;
    /**
    * Zid refresh token
    */
    'zidRefreshToken'?: string;
    /**
    * Flipkart Client ID
    */
    'flipkartClientId'?: string;
    /**
    * Flipkart Client Secret
    */
    'flipkartClientSecret'?: string;
    /**
    * Allegro Client ID
    */
    'allegroClientId'?: string;
    /**
    * Allegro Client Secret
    */
    'allegroClientSecret'?: string;
    /**
    * Allegro Access Token
    */
    'allegroAccessToken'?: string;
    /**
    * Allegro Refresh Token
    */
    'allegroRefreshToken'?: string;
    /**
    * Allegro Environment
    */
    'allegroEnvironment'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cartId",
            "baseName": "cart_id",
            "type": "CartCreateCartIdEnum",
            "format": ""
        },
        {
            "name": "storeUrl",
            "baseName": "store_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "bridgeUrl",
            "baseName": "bridge_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeRoot",
            "baseName": "store_root",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeKey",
            "baseName": "store_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "sharedSecret",
            "baseName": "shared_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "validateVersion",
            "baseName": "validate_version",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verify",
            "baseName": "verify",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "dbTablesPrefix",
            "baseName": "db_tables_prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "userAgent",
            "baseName": "user_agent",
            "type": "string",
            "format": ""
        },
        {
            "name": "ftpHost",
            "baseName": "ftp_host",
            "type": "string",
            "format": ""
        },
        {
            "name": "ftpUser",
            "baseName": "ftp_user",
            "type": "string",
            "format": ""
        },
        {
            "name": "ftpPassword",
            "baseName": "ftp_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "ftpPort",
            "baseName": "ftp_port",
            "type": "number",
            "format": ""
        },
        {
            "name": "ftpStoreDir",
            "baseName": "ftp_store_dir",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKey3dcart",
            "baseName": "apiKey_3dcart",
            "type": "string",
            "format": ""
        },
        {
            "name": "adminAccount",
            "baseName": "AdminAccount",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiPath",
            "baseName": "ApiPath",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKeyBigcommerce",
            "baseName": "ApiKey_Bigcommerce",
            "type": "string",
            "format": ""
        },
        {
            "name": "clientId",
            "baseName": "client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKeyShopify",
            "baseName": "apiKey_shopify",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiPassword",
            "baseName": "apiPassword",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessTokenShopify",
            "baseName": "accessToken_shopify",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiUsername",
            "baseName": "apiUsername",
            "type": "string",
            "format": ""
        },
        {
            "name": "encryptedPassword",
            "baseName": "EncryptedPassword",
            "type": "string",
            "format": ""
        },
        {
            "name": "login",
            "baseName": "Login",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiUserAdnsf",
            "baseName": "apiUser_adnsf",
            "type": "string",
            "format": ""
        },
        {
            "name": "apiPass",
            "baseName": "apiPass",
            "type": "string",
            "format": ""
        },
        {
            "name": "privateKey",
            "baseName": "privateKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "appToken",
            "baseName": "appToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "etsyKeystring",
            "baseName": "etsy_keystring",
            "type": "string",
            "format": ""
        },
        {
            "name": "etsySharedSecret",
            "baseName": "etsy_shared_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenSecret",
            "baseName": "tokenSecret",
            "type": "string",
            "format": ""
        },
        {
            "name": "etsyClientId",
            "baseName": "etsy_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "etsyRefreshToken",
            "baseName": "etsy_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayClientId",
            "baseName": "ebay_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayClientSecret",
            "baseName": "ebay_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayRuname",
            "baseName": "ebay_runame",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayAccessToken",
            "baseName": "ebay_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayRefreshToken",
            "baseName": "ebay_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebayEnvironment",
            "baseName": "ebay_environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "ebaySiteId",
            "baseName": "ebay_site_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "dwClientId",
            "baseName": "dw_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "dwApiPass",
            "baseName": "dw_api_pass",
            "type": "string",
            "format": ""
        },
        {
            "name": "demandwareUserName",
            "baseName": "demandware_user_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "demandwareUserPassword",
            "baseName": "demandware_user_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sellerId",
            "baseName": "seller_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "hybrisClientId",
            "baseName": "hybris_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "hybrisClientSecret",
            "baseName": "hybris_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "hybrisUsername",
            "baseName": "hybris_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "hybrisPassword",
            "baseName": "hybris_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "hybrisWebsites",
            "baseName": "hybris_websites",
            "type": "Array<AccountCartAddHybrisWebsitesInner>",
            "format": ""
        },
        {
            "name": "walmartClientId",
            "baseName": "walmart_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "walmartClientSecret",
            "baseName": "walmart_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "walmartEnvironment",
            "baseName": "walmart_environment",
            "type": "string",
            "format": ""
        },
        {
            "name": "walmartChannelType",
            "baseName": "walmart_channel_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "walmartRegion",
            "baseName": "walmart_region",
            "type": "string",
            "format": ""
        },
        {
            "name": "lightspeedApiKey",
            "baseName": "lightspeed_api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "lightspeedApiSecret",
            "baseName": "lightspeed_api_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "shoplazzaAccessToken",
            "baseName": "shoplazza_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "shoplazzaSharedSecret",
            "baseName": "shoplazza_shared_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "shopwareAccessKey",
            "baseName": "shopware_access_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "shopwareApiKey",
            "baseName": "shopware_api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "shopwareApiSecret",
            "baseName": "shopware_api_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "commercehqApiKey",
            "baseName": "commercehq_api_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "commercehqApiPassword",
            "baseName": "commercehq_api_password",
            "type": "string",
            "format": ""
        },
        {
            "name": "_3dcartPrivateKey",
            "baseName": "3dcart_private_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "_3dcartAccessToken",
            "baseName": "3dcart_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "wcConsumerKey",
            "baseName": "wc_consumer_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "wcConsumerSecret",
            "baseName": "wc_consumer_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "magentoConsumerKey",
            "baseName": "magento_consumer_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "magentoConsumerSecret",
            "baseName": "magento_consumer_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "magentoAccessToken",
            "baseName": "magento_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "magentoTokenSecret",
            "baseName": "magento_token_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "prestashopWebserviceKey",
            "baseName": "prestashop_webservice_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "wixAppId",
            "baseName": "wix_app_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "wixAppSecretKey",
            "baseName": "wix_app_secret_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "wixInstanceId",
            "baseName": "wix_instance_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "wixRefreshToken",
            "baseName": "wix_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "mercadoLibreAppId",
            "baseName": "mercado_libre_app_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mercadoLibreAppSecretKey",
            "baseName": "mercado_libre_app_secret_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "mercadoLibreRefreshToken",
            "baseName": "mercado_libre_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "zidClientId",
            "baseName": "zid_client_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "zidClientSecret",
            "baseName": "zid_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "zidAccessToken",
            "baseName": "zid_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "zidAuthorization",
            "baseName": "zid_authorization",
            "type": "string",
            "format": ""
        },
        {
            "name": "zidRefreshToken",
            "baseName": "zid_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "flipkartClientId",
            "baseName": "flipkart_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "flipkartClientSecret",
            "baseName": "flipkart_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "allegroClientId",
            "baseName": "allegro_client_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "allegroClientSecret",
            "baseName": "allegro_client_secret",
            "type": "string",
            "format": ""
        },
        {
            "name": "allegroAccessToken",
            "baseName": "allegro_access_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "allegroRefreshToken",
            "baseName": "allegro_refresh_token",
            "type": "string",
            "format": ""
        },
        {
            "name": "allegroEnvironment",
            "baseName": "allegro_environment",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartCreate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CartCreateCartIdEnum {
    _3DCart = '3DCart',
    _3DCartApi = '3DCartApi',
    AceShop = 'AceShop',
    AmazonSp = 'AmazonSP',
    AspDotNetStorefront = 'AspDotNetStorefront',
    BigCartel = 'BigCartel',
    BigcommerceApi = 'BigcommerceApi',
    Bol = 'Bol',
    CommerceHq = 'CommerceHQ',
    Creloaded = 'Creloaded',
    Cscart = 'Cscart',
    Cubecart = 'Cubecart',
    Demandware = 'Demandware',
    EBay = 'EBay',
    Ecwid = 'Ecwid',
    EtsyApiv3 = 'EtsyAPIv3',
    Flipkart = 'Flipkart',
    Gambio = 'Gambio',
    Hybris = 'Hybris',
    JooCart = 'JooCart',
    Lazada = 'Lazada',
    LightSpeed = 'LightSpeed',
    Magento1212 = 'Magento1212',
    Magento2Api = 'Magento2Api',
    MercadoLibre = 'MercadoLibre',
    MijoShop = 'MijoShop',
    Miva = 'Miva',
    Neto = 'Neto',
    Opencart14 = 'Opencart14',
    Oscmax2 = 'Oscmax2',
    Oscommerce22ms2 = 'Oscommerce22ms2',
    Otto = 'Otto',
    Oxid = 'Oxid',
    Pinnacle = 'Pinnacle',
    Prestashop = 'Prestashop',
    PrestashopApi = 'PrestashopApi',
    SsPremium = 'SSPremium',
    Salla = 'Salla',
    Shopify = 'Shopify',
    Shopee = 'Shopee',
    Shoplazza = 'Shoplazza',
    Shopline = 'Shopline',
    Shopware = 'Shopware',
    ShopwareApi = 'ShopwareApi',
    Square = 'Square',
    Squarespace = 'Squarespace',
    Temu = 'Temu',
    Tiendanube = 'Tiendanube',
    TikTokShop = 'TikTokShop',
    Tomatocart = 'Tomatocart',
    Ubercart = 'Ubercart',
    Virtuemart = 'Virtuemart',
    Volusion = 'Volusion',
    WPecommerce = 'WPecommerce',
    Walmart = 'Walmart',
    WebAsyst = 'WebAsyst',
    Wix = 'Wix',
    Woocommerce = 'Woocommerce',
    WoocommerceApi = 'WoocommerceApi',
    Xcart = 'Xcart',
    Xtcommerce = 'Xtcommerce',
    XtcommerceVeyton = 'XtcommerceVeyton',
    Zencart137 = 'Zencart137',
    Zid = 'Zid',
    Zoey = 'Zoey',
    Zoho = 'Zoho'
}

