/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { CatalogPriceRuleAction } from '../models/CatalogPriceRuleAction';
import { CouponCondition } from '../models/CouponCondition';
import { HttpFile } from '../http/http';

export class CatalogPriceRule {
    'id'?: string;
    'gid'?: string | null;
    'type'?: string | null;
    'name'?: string | null;
    'description'?: string | null;
    'shortDescription'?: string | null;
    'avail'?: boolean | null;
    'actions'?: Array<CatalogPriceRuleAction>;
    'createdTime'?: A2CDateTime | null;
    'dateStart'?: A2CDateTime | null;
    'dateEnd'?: A2CDateTime | null;
    'usageCount'?: number | null;
    'conditions'?: Array<CouponCondition>;
    'usesPerOrderLimit'?: number | null;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "gid",
            "baseName": "gid",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "avail",
            "baseName": "avail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<CatalogPriceRuleAction>",
            "format": ""
        },
        {
            "name": "createdTime",
            "baseName": "created_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "date_start",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "dateEnd",
            "baseName": "date_end",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "usageCount",
            "baseName": "usage_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<CouponCondition>",
            "format": ""
        },
        {
            "name": "usesPerOrderLimit",
            "baseName": "uses_per_order_limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CatalogPriceRule.attributeTypeMap;
    }

    public constructor() {
    }
}
