/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryAddBatchPayloadInner } from '../models/CategoryAddBatchPayloadInner';
import { HttpFile } from '../http/http';

export class CategoryAddBatch {
    /**
    * Contains an array of categories objects. The list of properties may vary depending on the specific platform.
    */
    'payload': Array<CategoryAddBatchPayloadInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<CategoryAddBatchPayloadInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CategoryAddBatch.attributeTypeMap;
    }

    public constructor() {
    }
}
