/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CategoryFind200ResponseResultCategoryInner } from '../models/CategoryFind200ResponseResultCategoryInner';
import { HttpFile } from '../http/http';

export class CategoryFind200ResponseResult {
    'category'?: Array<CategoryFind200ResponseResultCategoryInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "category",
            "baseName": "category",
            "type": "Array<CategoryFind200ResponseResultCategoryInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CategoryFind200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
