/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { CouponAction } from '../models/CouponAction';
import { CouponCode } from '../models/CouponCode';
import { CouponCondition } from '../models/CouponCondition';
import { CouponHistory } from '../models/CouponHistory';
import { HttpFile } from '../http/http';

export class Coupon {
    'id'?: string;
    'code'?: string | null;
    'codes'?: Array<CouponCode>;
    'name'?: string | null;
    'description'?: string | null;
    'actions'?: Array<CouponAction>;
    'dateStart'?: A2CDateTime | null;
    'dateEnd'?: A2CDateTime | null;
    'avail'?: boolean | null;
    'priority'?: number | null;
    'usedTimes'?: number | null;
    'usageLimit'?: number | null;
    'usageLimitPerCustomer'?: number | null;
    'logicOperator'?: string | null;
    'conditions'?: Array<CouponCondition>;
    'usageHistory'?: Array<CouponHistory>;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "codes",
            "baseName": "codes",
            "type": "Array<CouponCode>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<CouponAction>",
            "format": ""
        },
        {
            "name": "dateStart",
            "baseName": "date_start",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "dateEnd",
            "baseName": "date_end",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "avail",
            "baseName": "avail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": ""
        },
        {
            "name": "usedTimes",
            "baseName": "used_times",
            "type": "number",
            "format": ""
        },
        {
            "name": "usageLimit",
            "baseName": "usage_limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "usageLimitPerCustomer",
            "baseName": "usage_limit_per_customer",
            "type": "number",
            "format": ""
        },
        {
            "name": "logicOperator",
            "baseName": "logic_operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<CouponCondition>",
            "format": ""
        },
        {
            "name": "usageHistory",
            "baseName": "usage_history",
            "type": "Array<CouponHistory>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Coupon.attributeTypeMap;
    }

    public constructor() {
    }
}
