/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CouponCondition } from '../models/CouponCondition';
import { HttpFile } from '../http/http';

export class CouponAction {
    'scope'?: string;
    'applyTo'?: string;
    'amount'?: number;
    'currencyCode'?: string;
    'includeTax'?: boolean;
    'type'?: string;
    'discountedQuantity'?: number;
    'discountQuantityStep'?: number;
    'logicOperator'?: string;
    'conditions'?: Array<CouponCondition>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "scope",
            "baseName": "scope",
            "type": "string",
            "format": ""
        },
        {
            "name": "applyTo",
            "baseName": "apply_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "currencyCode",
            "baseName": "currency_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "includeTax",
            "baseName": "include_tax",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "discountedQuantity",
            "baseName": "discounted_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "discountQuantityStep",
            "baseName": "discount_quantity_step",
            "type": "number",
            "format": ""
        },
        {
            "name": "logicOperator",
            "baseName": "logic_operator",
            "type": "string",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<CouponCondition>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CouponAction.attributeTypeMap;
    }

    public constructor() {
    }
}
