/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerAddAddressInner } from '../models/CustomerAddAddressInner';
import { CustomerAddConsentsInner } from '../models/CustomerAddConsentsInner';
import { HttpFile } from '../http/http';

export class CustomerAdd {
    /**
    * Defines customer\'s email
    */
    'email': string;
    /**
    * Defines customer\'s first name
    */
    'firstName'?: string;
    /**
    * Defines customer\'s last name
    */
    'lastName'?: string;
    /**
    * Defines customer\'s unique password
    */
    'password'?: string;
    /**
    * Defines the group where the customer
    */
    'group'?: string;
    /**
    * Customer group_id
    */
    'groupId'?: string;
    /**
    * Groups that will be assigned to a customer
    */
    'groupIds'?: string;
    /**
    * Defines customer\'s status
    */
    'status'?: string;
    /**
    * Entity\'s date creation
    */
    'createdTime'?: string;
    /**
    * Entity\'s date modification
    */
    'modifiedTime'?: string;
    /**
    * Specifies customer\'s login name
    */
    'login'?: string;
    /**
    * Defines customer\'s last login time
    */
    'lastLogin'?: string;
    /**
    * Defines customer\'s birthday
    */
    'birthDay'?: string;
    /**
    * Defines whether the newsletter subscription is available for the user
    */
    'newsLetterSubscription'?: boolean;
    /**
    * Defines consents to notifications
    */
    'consents'?: Array<CustomerAddConsentsInner>;
    /**
    * Defines customer\'s gender
    */
    'gender'?: string;
    /**
    * Link to customer website
    */
    'website'?: string;
    /**
    * Defines customer\'s fax
    */
    'fax'?: string;
    /**
    * Defines customer\'s company
    */
    'company'?: string;
    /**
    * Defines customer\'s phone number
    */
    'phone'?: string;
    /**
    * The customer note.
    */
    'note'?: string;
    /**
    * Specifies ISO code or name of country
    */
    'country'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    /**
    * A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    */
    'idempotencyKey'?: string;
    'address'?: Array<CustomerAddAddressInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdTime",
            "baseName": "created_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "modifiedTime",
            "baseName": "modified_time",
            "type": "string",
            "format": ""
        },
        {
            "name": "login",
            "baseName": "login",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastLogin",
            "baseName": "last_login",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDay",
            "baseName": "birth_day",
            "type": "string",
            "format": ""
        },
        {
            "name": "newsLetterSubscription",
            "baseName": "news_letter_subscription",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "consents",
            "baseName": "consents",
            "type": "Array<CustomerAddConsentsInner>",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        },
        {
            "name": "fax",
            "baseName": "fax",
            "type": "string",
            "format": ""
        },
        {
            "name": "company",
            "baseName": "company",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Array<CustomerAddAddressInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
