/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CustomerAddAddressInner {
    /**
    * Specifies customer\'s address type
    */
    'addressBookType'?: string;
    /**
    * Specifies customer\'s first name in the address book
    */
    'addressBookFirstName'?: string;
    /**
    * Specifies customer\'s last name in the address book
    */
    'addressBookLastName'?: string;
    /**
    * Specifies customer\'s company name in the address book
    */
    'addressBookCompany'?: string;
    /**
    * Specifies customer\'s fax in the address book
    */
    'addressBookFax'?: string;
    /**
    * Specifies customer\'s phone number in the address book
    */
    'addressBookPhone'?: string;
    /**
    * Specifies customer\'s mobile phone number in the address book
    */
    'addressBookPhoneMobile'?: string;
    /**
    * Specifies customer\'s website in the address book
    */
    'addressBookWebsite'?: string;
    /**
    * Specifies customer\'s first address in the address book
    */
    'addressBookAddress1'?: string;
    /**
    * Specifies customer\'s second address in the address book
    */
    'addressBookAddress2'?: string;
    /**
    * Specifies customer\'s city in the address book
    */
    'addressBookCity'?: string;
    /**
    * ISO code or name of country
    */
    'addressBookCountry'?: string;
    /**
    * ISO code or name of state.
    */
    'addressBookState'?: string;
    /**
    * Specifies customer\'s postcode
    */
    'addressBookPostcode'?: string;
    /**
    * Specifies customer\'s gender
    */
    'addressBookGender'?: string;
    /**
    * Specifies customer\'s region
    */
    'addressBookRegion'?: string;
    /**
    * Defines whether the address is used by default
    */
    'addressBookDefault'?: boolean;
    /**
    * Add Tax Id
    */
    'addressBookTaxId'?: string;
    /**
    * The national ID card number of this person, or a unique tax identification number.
    */
    'addressBookIdentificationNumber'?: string;
    /**
    * Specifies customer\'s alias in the address book
    */
    'addressBookAlias'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addressBookType",
            "baseName": "address_book_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookFirstName",
            "baseName": "address_book_first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookLastName",
            "baseName": "address_book_last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookCompany",
            "baseName": "address_book_company",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookFax",
            "baseName": "address_book_fax",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookPhone",
            "baseName": "address_book_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookPhoneMobile",
            "baseName": "address_book_phone_mobile",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookWebsite",
            "baseName": "address_book_website",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookAddress1",
            "baseName": "address_book_address1",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookAddress2",
            "baseName": "address_book_address2",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookCity",
            "baseName": "address_book_city",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookCountry",
            "baseName": "address_book_country",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookState",
            "baseName": "address_book_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookPostcode",
            "baseName": "address_book_postcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookGender",
            "baseName": "address_book_gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookRegion",
            "baseName": "address_book_region",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookDefault",
            "baseName": "address_book_default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "addressBookTaxId",
            "baseName": "address_book_tax_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookIdentificationNumber",
            "baseName": "address_book_identification_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressBookAlias",
            "baseName": "address_book_alias",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerAddAddressInner.attributeTypeMap;
    }

    public constructor() {
    }
}
