/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerAddConsentsInner } from '../models/CustomerAddConsentsInner';
import { CustomerUpdateAddressInner } from '../models/CustomerUpdateAddressInner';
import { HttpFile } from '../http/http';

export class CustomerUpdate {
    /**
    * Entity id
    */
    'id'?: string;
    /**
    * Customer group_id
    */
    'groupId'?: string;
    /**
    * Groups that will be assigned to a customer
    */
    'groupIds'?: string;
    /**
    * Defines the group where the customer
    */
    'group'?: string;
    /**
    * Defines customer\'s email
    */
    'email'?: string;
    /**
    * Defines customer\'s phone number
    */
    'phone'?: string;
    /**
    * Defines customer\'s first name
    */
    'firstName'?: string;
    /**
    * Defines customer\'s last name
    */
    'lastName'?: string;
    /**
    * Defines customer\'s birthday
    */
    'birthDay'?: string;
    /**
    * Defines whether the newsletter subscription is available for the user
    */
    'newsLetterSubscription'?: boolean;
    /**
    * Defines consents to notifications
    */
    'consents'?: Array<CustomerAddConsentsInner>;
    /**
    * Customer tags
    */
    'tags'?: string;
    /**
    * Defines customer\'s gender
    */
    'gender'?: string;
    /**
    * The customer note.
    */
    'note'?: string;
    /**
    * Defines customer\'s status
    */
    'status'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    'address'?: Array<CustomerUpdateAddressInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstName",
            "baseName": "first_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "last_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDay",
            "baseName": "birth_day",
            "type": "string",
            "format": ""
        },
        {
            "name": "newsLetterSubscription",
            "baseName": "news_letter_subscription",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "consents",
            "baseName": "consents",
            "type": "Array<CustomerAddConsentsInner>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "string",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Array<CustomerUpdateAddressInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}
