/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CouponHistory } from '../models/CouponHistory';
import { HttpFile } from '../http/http';

export class GiftCard {
    'id'?: string;
    'code'?: string;
    'name'?: string;
    'type'?: string;
    'currencyCode'?: string;
    'amount'?: number;
    'initialAmount'?: number;
    'status'?: string;
    'createdAt'?: string;
    'availTo'?: string;
    'freeProductIds'?: string;
    'message'?: string;
    'issuerEmail'?: string;
    'recipientEmail'?: string;
    'issuerName'?: string;
    'recipientName'?: string;
    'usageHistory'?: Array<CouponHistory>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "currencyCode",
            "baseName": "currency_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "initialAmount",
            "baseName": "initial_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "availTo",
            "baseName": "avail_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "freeProductIds",
            "baseName": "free_product_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerEmail",
            "baseName": "issuer_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientEmail",
            "baseName": "recipient_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuerName",
            "baseName": "issuer_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientName",
            "baseName": "recipient_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "usageHistory",
            "baseName": "usage_history",
            "type": "Array<CouponHistory>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GiftCard.attributeTypeMap;
    }

    public constructor() {
    }
}
