/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Image } from '../models/Image';
import { ProductOption } from '../models/ProductOption';
import { HttpFile } from '../http/http';

export class MarketplaceProduct {
    'id'?: string;
    'type'?: string;
    'uAsin'?: string;
    'uEan'?: string;
    'uGtin'?: string;
    'uIsbn'?: string;
    'uMpn'?: string;
    'uUpc'?: string;
    'name'?: string;
    'description'?: string;
    'url'?: string;
    'price'?: number;
    'images'?: Array<Image>;
    'productOptions'?: Array<ProductOption>;
    'manufacturer'?: string;
    'brand'?: string;
    'weight'?: number;
    'weightUnit'?: string;
    'dimensionsUnit'?: string;
    'width'?: number;
    'height'?: number;
    'length'?: number;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "uAsin",
            "baseName": "u_asin",
            "type": "string",
            "format": ""
        },
        {
            "name": "uEan",
            "baseName": "u_ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "uGtin",
            "baseName": "u_gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "uIsbn",
            "baseName": "u_isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "uMpn",
            "baseName": "u_mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "uUpc",
            "baseName": "u_upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Image>",
            "format": ""
        },
        {
            "name": "productOptions",
            "baseName": "product_options",
            "type": "Array<ProductOption>",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "brand",
            "baseName": "brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "dimensionsUnit",
            "baseName": "dimensions_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MarketplaceProduct.attributeTypeMap;
    }

    public constructor() {
    }
}
