/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { OrderStatusRefundItem } from '../models/OrderStatusRefundItem';
import { HttpFile } from '../http/http';

export class OrderStatusRefund {
    'shipping'?: number;
    'fee'?: number;
    'tax'?: number;
    'totalRefunded'?: number;
    'time'?: A2CDateTime;
    'comment'?: string;
    'refundedItems'?: Array<OrderStatusRefundItem>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipping",
            "baseName": "shipping",
            "type": "number",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number",
            "format": ""
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalRefunded",
            "baseName": "total_refunded",
            "type": "number",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "refundedItems",
            "baseName": "refunded_items",
            "type": "Array<OrderStatusRefundItem>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderStatusRefund.attributeTypeMap;
    }

    public constructor() {
    }
}
