/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderReturnAddOrderProductsInner } from '../models/OrderReturnAddOrderProductsInner';
import { HttpFile } from '../http/http';

export class OrderReturnAdd {
    /**
    * Defines the order id
    */
    'orderId'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    /**
    * Defines return request status
    */
    'returnStatusId': string;
    /**
    * Defines return request action
    */
    'returnActionId': string;
    /**
    * Defines return request reason
    */
    'returnReasonId': string;
    /**
    * Defines return request reason
    */
    'returnReason'?: string;
    /**
    * Boolean, whether or not to add the line items back to the store inventory.
    */
    'itemRestock'?: boolean;
    /**
    * Specifies staff note
    */
    'staffNote'?: string;
    /**
    * Specifies return comment
    */
    'comment'?: string;
    /**
    * Send notifications to customer after order was created
    */
    'sendNotifications'?: boolean;
    /**
    * Defines return reject reason
    */
    'rejectReason'?: string;
    'orderProducts': Array<OrderReturnAddOrderProductsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnStatusId",
            "baseName": "return_status_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnActionId",
            "baseName": "return_action_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnReasonId",
            "baseName": "return_reason_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnReason",
            "baseName": "return_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemRestock",
            "baseName": "item_restock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "staffNote",
            "baseName": "staff_note",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendNotifications",
            "baseName": "send_notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rejectReason",
            "baseName": "reject_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderProducts",
            "baseName": "order_products",
            "type": "Array<OrderReturnAddOrderProductsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderReturnAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
