/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderRefundAdd200ResponseResult {
    'refundId'?: string;
    'additionalRefundIds'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "refundId",
            "baseName": "refund_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalRefundIds",
            "baseName": "additional_refund_ids",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderRefundAdd200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
