/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemOption } from '../models/OrderItemOption';
import { HttpFile } from '../http/http';

export class OrderItem {
    'productId'?: string | null;
    'orderProductId'?: string | null;
    'model'?: string | null;
    'name'?: string;
    'price'?: number;
    'priceIncTax'?: number | null;
    'quantity'?: number | null;
    'discountAmount'?: number | null;
    'totalPrice'?: number | null;
    'taxPercent'?: number | null;
    'taxValue'?: number | null;
    'taxValueAfterDiscount'?: number | null;
    'options'?: Array<OrderItemOption>;
    'variantId'?: string | null;
    'weightUnit'?: string | null;
    'weight'?: number | null;
    'barcode'?: string | null;
    'parentOrderProductId'?: string | null;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderProductId",
            "baseName": "order_product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceIncTax",
            "baseName": "price_inc_tax",
            "type": "number",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "discountAmount",
            "baseName": "discount_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPrice",
            "baseName": "total_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxPercent",
            "baseName": "tax_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxValue",
            "baseName": "tax_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxValueAfterDiscount",
            "baseName": "tax_value_after_discount",
            "type": "number",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<OrderItemOption>",
            "format": ""
        },
        {
            "name": "variantId",
            "baseName": "variant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentOrderProductId",
            "baseName": "parent_order_product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderItem.attributeTypeMap;
    }

    public constructor() {
    }
}
