/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner } from '../models/OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner';
import { HttpFile } from '../http/http';

export class OrderPreestimateShippingListOrderItemInner {
    /**
    * Defines orders specified by order item id
    */
    'orderItemId': string;
    /**
    * Defines orders specified by order item model
    */
    'orderItemModel'?: string;
    /**
    * Defines orders specified by order item quantity
    */
    'orderItemQuantity': number;
    /**
    * Defines orders specified by order item weight
    */
    'orderItemWeight'?: number;
    /**
    * Ordered product variant. Where x is order item ID
    */
    'orderItemVariantId'?: string;
    'orderItemOption'?: Array<OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderItemId",
            "baseName": "order_item_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemModel",
            "baseName": "order_item_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemQuantity",
            "baseName": "order_item_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemWeight",
            "baseName": "order_item_weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemVariantId",
            "baseName": "order_item_variant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemOption",
            "baseName": "order_item_option",
            "type": "Array<OrderPreestimateShippingListOrderItemInnerOrderItemOptionInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderPreestimateShippingListOrderItemInner.attributeTypeMap;
    }

    public constructor() {
    }
}
