/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { HttpFile } from '../http/http';

export class OrderTransaction {
    'id'?: string;
    'transactionId'?: string;
    'orderId'?: string;
    'parentId'?: string;
    'description'?: string;
    'status'?: string;
    'gateway'?: string;
    'referenceNumber'?: string;
    'currency'?: string;
    'amount'?: number;
    'createdTime'?: A2CDateTime;
    'settlementCurrency'?: string;
    'settlementAmount'?: number;
    'settlementCreatedTime'?: A2CDateTime;
    'cardBrand'?: string;
    'cardBin'?: string;
    'cardLastFour'?: string;
    'avsStreetRespCode'?: string;
    'avsPostalRespCode'?: string;
    'avsMessage'?: string;
    'cvvCode'?: string;
    'cvvMessage'?: string;
    'isTestMode'?: boolean;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionId",
            "baseName": "transaction_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "gateway",
            "baseName": "gateway",
            "type": "string",
            "format": ""
        },
        {
            "name": "referenceNumber",
            "baseName": "reference_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdTime",
            "baseName": "created_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "settlementCurrency",
            "baseName": "settlement_currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "settlementAmount",
            "baseName": "settlement_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "settlementCreatedTime",
            "baseName": "settlement_created_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "cardBrand",
            "baseName": "card_brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardBin",
            "baseName": "card_bin",
            "type": "string",
            "format": ""
        },
        {
            "name": "cardLastFour",
            "baseName": "card_last_four",
            "type": "string",
            "format": ""
        },
        {
            "name": "avsStreetRespCode",
            "baseName": "avs_street_resp_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "avsPostalRespCode",
            "baseName": "avs_postal_resp_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "avsMessage",
            "baseName": "avs_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "cvvCode",
            "baseName": "cvv_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "cvvMessage",
            "baseName": "cvv_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "isTestMode",
            "baseName": "is_test_mode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}
