/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderShipmentTrackingAdd {
    /**
    * Defines the order id
    */
    'orderId'?: string;
    /**
    * Shipment id indicates the number of delivery
    */
    'shipmentId': string;
    /**
    * Defines tracking carrier id
    */
    'carrierId'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    /**
    * Defines name of the company which provides shipment tracking
    */
    'trackingProvider'?: string;
    /**
    * Defines tracking number
    */
    'trackingNumber': string;
    /**
    * Defines custom tracking link
    */
    'trackingLink'?: string;
    /**
    * Send notifications to customer after tracking was created
    */
    'sendNotifications'?: boolean;
    /**
    * A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    */
    'idempotencyKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentId",
            "baseName": "shipment_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "carrierId",
            "baseName": "carrier_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingProvider",
            "baseName": "tracking_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingNumber",
            "baseName": "tracking_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingLink",
            "baseName": "tracking_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "sendNotifications",
            "baseName": "send_notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderShipmentTrackingAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
