/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemOption } from '../models/OrderItemOption';
import { HttpFile } from '../http/http';

export class OrderCalculateBundle {
    'productId'?: string;
    'sku'?: string;
    'name'?: string;
    'quantity'?: number;
    'price'?: number;
    'priceIncTax'?: number;
    'taxRate'?: number;
    'unitDiscount'?: number;
    'weight'?: number | null;
    'weightUnit'?: string | null;
    'barcode'?: string | null;
    'variantId'?: string | null;
    'options'?: Array<OrderItemOption>;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceIncTax",
            "baseName": "price_inc_tax",
            "type": "number",
            "format": ""
        },
        {
            "name": "taxRate",
            "baseName": "tax_rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "unitDiscount",
            "baseName": "unit_discount",
            "type": "number",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "variantId",
            "baseName": "variant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<OrderItemOption>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCalculateBundle.attributeTypeMap;
    }

    public constructor() {
    }
}
