/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderAddOrderItemInnerOrderItemOptionInner } from '../models/OrderAddOrderItemInnerOrderItemOptionInner';
import { OrderAddOrderItemInnerOrderItemPropertyInner } from '../models/OrderAddOrderItemInnerOrderItemPropertyInner';
import { HttpFile } from '../http/http';

export class OrderAddOrderItemInner {
    /**
    * Defines orders specified by order item id
    */
    'orderItemId': string;
    /**
    * Defines orders specified by order item name
    */
    'orderItemName': string;
    /**
    * Defines orders specified by order item model
    */
    'orderItemModel'?: string;
    /**
    * Defines orders specified by order item price
    */
    'orderItemPrice': number;
    /**
    * Defines orders specified by order item quantity
    */
    'orderItemQuantity': number;
    /**
    * Defines orders specified by order item weight
    */
    'orderItemWeight'?: number;
    /**
    * Ordered product variant. Where x is order item ID
    */
    'orderItemVariantId'?: string;
    /**
    * Percentage of tax for product order
    */
    'orderItemTax'?: number;
    /**
    * Defines if item price includes tax
    */
    'orderItemPriceIncludesTax'?: boolean;
    /**
    * Index of the parent grouped/bundle product
    */
    'orderItemParent'?: number;
    /**
    * Option name of the parent grouped/bundle product
    */
    'orderItemParentOptionName'?: string;
    /**
    * Indicates whether subitems of the grouped/bundle product can be refunded separately
    */
    'orderItemAllowRefundItemsSeparately'?: boolean;
    /**
    * Indicates whether subitems of the grouped/bundle product can be shipped separately
    */
    'orderItemAllowShipItemsSeparately'?: boolean;
    'orderItemOption'?: Array<OrderAddOrderItemInnerOrderItemOptionInner>;
    'orderItemProperty'?: Array<OrderAddOrderItemInnerOrderItemPropertyInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderItemId",
            "baseName": "order_item_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemName",
            "baseName": "order_item_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemModel",
            "baseName": "order_item_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemPrice",
            "baseName": "order_item_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemQuantity",
            "baseName": "order_item_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemWeight",
            "baseName": "order_item_weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemVariantId",
            "baseName": "order_item_variant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemTax",
            "baseName": "order_item_tax",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemPriceIncludesTax",
            "baseName": "order_item_price_includes_tax",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "orderItemParent",
            "baseName": "order_item_parent",
            "type": "number",
            "format": ""
        },
        {
            "name": "orderItemParentOptionName",
            "baseName": "order_item_parent_option_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemAllowRefundItemsSeparately",
            "baseName": "order_item_allow_refund_items_separately",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "orderItemAllowShipItemsSeparately",
            "baseName": "order_item_allow_ship_items_separately",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "orderItemOption",
            "baseName": "order_item_option",
            "type": "Array<OrderAddOrderItemInnerOrderItemOptionInner>",
            "format": ""
        },
        {
            "name": "orderItemProperty",
            "baseName": "order_item_property",
            "type": "Array<OrderAddOrderItemInnerOrderItemPropertyInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderAddOrderItemInner.attributeTypeMap;
    }

    public constructor() {
    }
}
