/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderCalculateOrderItemInnerOrderItemOptionInner {
    /**
    * Ordered Product Option Name. Where x is order item ID, y is order item option ID
    */
    'orderItemOptionName'?: string;
    /**
    * Ordered product option value Where x is order item ID, y - order item option ID
    */
    'orderItemOptionValue'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderItemOptionName",
            "baseName": "order_item_option_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderItemOptionValue",
            "baseName": "order_item_option_value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderCalculateOrderItemInnerOrderItemOptionInner.attributeTypeMap;
    }

    public constructor() {
    }
}
