/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderShipmentAddItemsInner } from '../models/OrderShipmentAddItemsInner';
import { OrderShipmentAddTrackingNumbersInner } from '../models/OrderShipmentAddTrackingNumbersInner';
import { HttpFile } from '../http/http';

export class OrderShipmentUpdate {
    /**
    * Shipment id indicates the number of delivery
    */
    'shipmentId': string;
    /**
    * Defines the order that will be updated
    */
    'orderId'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    /**
    * Defines company name that provide tracking of shipment
    */
    'shipmentProvider'?: string;
    /**
    * Defines shipment\'s tracking numbers that have to be added</br> How set tracking numbers to appropriate carrier:<ul><li>tracking_numbers[]=a2c.demo1,a2c.demo2 - set default carrier</li><li>tracking_numbers[<b>carrier_id</b>]=a2c.demo - set appropriate carrier</li></ul>To get the list of carriers IDs that are available in your store, use the <a href = \"https://api2cart.com/docs/#/cart/CartInfo\">cart.info</a > method
    */
    'trackingNumbers'?: Array<OrderShipmentAddTrackingNumbersInner>;
    /**
    * Defines custom tracking link
    */
    'trackingLink'?: string;
    /**
    * Defines shipment\'s status
    */
    'isShipped'?: boolean;
    /**
    * Defines the date of delivery
    */
    'deliveredAt'?: string;
    /**
    * Allows rewrite tracking numbers
    */
    'replace'?: boolean;
    /**
    * Send notifications to customer after order was created
    */
    'sendNotifications'?: boolean;
    /**
    * Defines name of the company which provides shipment tracking
    */
    'trackingProvider'?: string;
    /**
    * Defines items in the order that will be shipped
    */
    'items'?: Array<OrderShipmentAddItemsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipmentId",
            "baseName": "shipment_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentProvider",
            "baseName": "shipment_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingNumbers",
            "baseName": "tracking_numbers",
            "type": "Array<OrderShipmentAddTrackingNumbersInner>",
            "format": ""
        },
        {
            "name": "trackingLink",
            "baseName": "tracking_link",
            "type": "string",
            "format": ""
        },
        {
            "name": "isShipped",
            "baseName": "is_shipped",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deliveredAt",
            "baseName": "delivered_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "replace",
            "baseName": "replace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sendNotifications",
            "baseName": "send_notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "trackingProvider",
            "baseName": "tracking_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderShipmentAddItemsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderShipmentUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}
