/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderRefundAddItemsInner } from '../models/OrderRefundAddItemsInner';
import { HttpFile } from '../http/http';

export class OrderRefundAdd {
    /**
    * Defines the order for which the refund will be created.
    */
    'orderId'?: string;
    /**
    * Defines items in the order that will be refunded
    */
    'items'?: Array<OrderRefundAddItemsInner>;
    /**
    * Defines order refund amount.
    */
    'totalPrice'?: number;
    /**
    * Defines refund shipping amount.
    */
    'shippingPrice'?: number;
    /**
    * Specifies refund\'s fee price
    */
    'feePrice'?: number;
    /**
    * Refund reason, or some else message which assigned to refund.
    */
    'message'?: string;
    /**
    * Boolean, whether or not to add the line items back to the store inventory.
    */
    'itemRestock'?: boolean;
    /**
    * Send notifications to customer after refund was created
    */
    'sendNotifications'?: boolean;
    /**
    * Specifies an order creation date in format Y-m-d H:i:s
    */
    'date'?: string;
    /**
    * Indicates whether refund type is online
    */
    'isOnline'?: boolean;
    /**
    * A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    */
    'idempotencyKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderRefundAddItemsInner>",
            "format": ""
        },
        {
            "name": "totalPrice",
            "baseName": "total_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "shippingPrice",
            "baseName": "shipping_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "feePrice",
            "baseName": "fee_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemRestock",
            "baseName": "item_restock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sendNotifications",
            "baseName": "send_notifications",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOnline",
            "baseName": "is_online",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OrderRefundAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
