/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Plugin } from '../models/Plugin';
import { HttpFile } from '../http/http';

export class PluginList {
    'allPlugins'?: number | null;
    'plugins'?: Array<Plugin>;
    'additionalFields'?: any | null;
    'customFields'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allPlugins",
            "baseName": "all_plugins",
            "type": "number",
            "format": ""
        },
        {
            "name": "plugins",
            "baseName": "plugins",
            "type": "Array<Plugin>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PluginList.attributeTypeMap;
    }

    public constructor() {
    }
}
