/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductVariantUpdateOptionsInner } from '../models/ProductVariantUpdateOptionsInner';
import { HttpFile } from '../http/http';

export class ProductVariantUpdate {
    /**
    * Defines variant update specified by variant id
    */
    'id'?: string;
    /**
    * Defines product\'s id where the variant has to be updated
    */
    'productId'?: string;
    /**
    * Defines store id where the variant should be found
    */
    'storeId'?: string;
    /**
    * Language id
    */
    'langId'?: string;
    /**
    * Defines variant\'s options list
    */
    'options'?: Array<ProductVariantUpdateOptionsInner>;
    /**
    * Defines variant\'s name that has to be updated
    */
    'name'?: string;
    /**
    * Specifies variant\'s description
    */
    'description'?: string;
    /**
    * Defines short description
    */
    'shortDescription'?: string;
    /**
    * Specifies variant\'s model that has to be added
    */
    'model'?: string;
    /**
    * Defines new product\'s variant sku
    */
    'sku'?: string;
    /**
    * Set visibility status
    */
    'visible'?: string;
    /**
    * Defines product variant\'s status
    */
    'status'?: string;
    /**
    * Set backorder status
    */
    'backorderStatus'?: string;
    /**
    * Specify the quantity threshold below which the product is considered low in stock
    */
    'lowStockThreshold'?: number;
    /**
    * Specifies the set of visible/invisible product\'s variants for sale
    */
    'availableForSale'?: boolean;
    /**
    * Defines category\'s visibility status
    */
    'avail'?: boolean;
    /**
    * Defines as a default variant
    */
    'isDefault'?: boolean;
    /**
    * Specifies variant\'s free shipping flag that has to be added
    */
    'isFreeShipping'?: boolean;
    /**
    * Specifies whether a tax is charged
    */
    'taxable'?: boolean;
    /**
    * Defines tax classes where entity has to be added
    */
    'taxClassId'?: string;
    /**
    * Defines whether the product is virtual
    */
    'isVirtual'?: boolean;
    /**
    * Defines inventory tracking for product variant
    */
    'manageStock'?: boolean;
    /**
    * Set stock status
    */
    'inStock'?: boolean;
    /**
    * This parameter is used for selecting a warehouse where you need to set/modify a product quantity.
    */
    'warehouseId'?: string;
    /**
    * This parameter allows to reserve/unreserve product variants quantity.
    */
    'reserveQuantity'?: number;
    /**
    * Defines new products\' variants quantity
    */
    'quantity'?: number;
    /**
    * Defines the incremental changes in product quantity
    */
    'increaseQuantity'?: number;
    /**
    * Defines the decrement changes in product quantity
    */
    'reduceQuantity'?: number;
    /**
    * Defines new product\'s variant price
    */
    'price'?: number;
    /**
    * Defines new product\'s variant special price
    */
    'specialPrice'?: number;
    /**
    * Defines new product\'s retail price
    */
    'retailPrice'?: number;
    /**
    * Defines product\'s old price
    */
    'oldPrice'?: number;
    /**
    * Defines new product\'s cost price
    */
    'costPrice'?: number;
    /**
    * Specifies fixed cost shipping price
    */
    'fixedCostShippingPrice'?: number;
    /**
    * Defines the date of special price creation
    */
    'spriceCreate'?: string;
    /**
    * Defines the term of special price offer duration
    */
    'spriceExpire'?: string;
    /**
    * Unit for the price per unit. Must be in allowed list
    */
    'measureUnit'?: string;
    /**
    * Defines new product\'s unit price
    */
    'unitPrice'?: number;
    /**
    * Weight
    */
    'weight'?: number;
    /**
    * A barcode is a unique code composed of numbers used as a product identifier.
    */
    'barcode'?: string;
    /**
    * Defines product\'s width
    */
    'width'?: number;
    /**
    * Weight Unit
    */
    'weightUnit'?: string;
    /**
    * Defines product\'s height
    */
    'height'?: number;
    /**
    * Defines product\'s length
    */
    'length'?: number;
    /**
    * Global Trade Item Number. An GTIN is an identifier for trade items.
    */
    'gtin'?: string;
    /**
    * Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products.
    */
    'upc'?: string;
    /**
    * Manufacturer Part Number. A MPN is an identifier of a particular part design or material used.
    */
    'mpn'?: string;
    /**
    * European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products.
    */
    'ean'?: string;
    /**
    * International Standard Book Number. An ISBN is a unique identifier for books.
    */
    'isbn'?: string;
    /**
    * Harmonized System Code. An HSC is a 6-digit identifier that allows participating countries to classify traded goods on a common basis for customs purposes
    */
    'harmonizedSystemCode'?: string;
    /**
    * The country where the inventory item was made
    */
    'countryOfOrigin'?: string;
    /**
    * Defines unique meta title for each entity
    */
    'metaTitle'?: string;
    /**
    * Defines unique meta description of a entity
    */
    'metaDescription'?: string;
    /**
    * Defines unique meta keywords for each entity
    */
    'metaKeywords'?: string;
    /**
    * Specifies the product variant\'s manufacturer
    */
    'manufacturer'?: string;
    /**
    * Is reindex required
    */
    'reindex'?: boolean;
    /**
    * Is cache clear required
    */
    'clearCache'?: boolean;
    /**
    * The numeric ID of the processing profile (readiness state) for physical products in Etsy. You can find possible values in the \"cart.info\" API method response, in the field processing_profiles[]->readiness_state_id.
    */
    'processingProfileId'?: number;
    /**
    * A unique identifier associated with a specific request. Repeated requests with the same <strong>idempotency_key</strong> return a cached response without re-executing the business logic. <strong>Please note that the cache lifetime is 15 minutes.</strong>
    */
    'idempotencyKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "langId",
            "baseName": "lang_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<ProductVariantUpdateOptionsInner>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "backorderStatus",
            "baseName": "backorder_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "lowStockThreshold",
            "baseName": "low_stock_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "availableForSale",
            "baseName": "available_for_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "avail",
            "baseName": "avail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDefault",
            "baseName": "is_default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFreeShipping",
            "baseName": "is_free_shipping",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taxable",
            "baseName": "taxable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taxClassId",
            "baseName": "tax_class_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "manageStock",
            "baseName": "manage_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inStock",
            "baseName": "in_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reserveQuantity",
            "baseName": "reserve_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "increaseQuantity",
            "baseName": "increase_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "reduceQuantity",
            "baseName": "reduce_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "specialPrice",
            "baseName": "special_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "retailPrice",
            "baseName": "retail_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "oldPrice",
            "baseName": "old_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "costPrice",
            "baseName": "cost_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "fixedCostShippingPrice",
            "baseName": "fixed_cost_shipping_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "spriceCreate",
            "baseName": "sprice_create",
            "type": "string",
            "format": ""
        },
        {
            "name": "spriceExpire",
            "baseName": "sprice_expire",
            "type": "string",
            "format": ""
        },
        {
            "name": "measureUnit",
            "baseName": "measure_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitPrice",
            "baseName": "unit_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "gtin",
            "baseName": "gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "mpn",
            "baseName": "mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "ean",
            "baseName": "ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "harmonizedSystemCode",
            "baseName": "harmonized_system_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryOfOrigin",
            "baseName": "country_of_origin",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaTitle",
            "baseName": "meta_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaDescription",
            "baseName": "meta_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaKeywords",
            "baseName": "meta_keywords",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "reindex",
            "baseName": "reindex",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "clearCache",
            "baseName": "clear_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "processingProfileId",
            "baseName": "processing_profile_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "idempotencyKey",
            "baseName": "idempotency_key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}
