/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductFind200ResponseResultProductInner } from '../models/ProductFind200ResponseResultProductInner';
import { HttpFile } from '../http/http';

export class ProductFind200ResponseResult {
    'product'?: Array<ProductFind200ResponseResultProductInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "product",
            "baseName": "product",
            "type": "Array<ProductFind200ResponseResultProductInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductFind200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
