/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductAddPersonalizationQuestionsInner {
    'questionText': string;
    'instructions'?: string;
    'questionType': ProductAddPersonalizationQuestionsInnerQuestionTypeEnum;
    'required': boolean;
    'maxAllowedCharacters'?: number | null;
    'maxAllowedFiles'?: number | null;
    'options'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "questionText",
            "baseName": "question_text",
            "type": "string",
            "format": ""
        },
        {
            "name": "instructions",
            "baseName": "instructions",
            "type": "string",
            "format": ""
        },
        {
            "name": "questionType",
            "baseName": "question_type",
            "type": "ProductAddPersonalizationQuestionsInnerQuestionTypeEnum",
            "format": ""
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxAllowedCharacters",
            "baseName": "max_allowed_characters",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxAllowedFiles",
            "baseName": "max_allowed_files",
            "type": "number",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddPersonalizationQuestionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductAddPersonalizationQuestionsInnerQuestionTypeEnum {
    TextInput = 'text_input',
    Dropdown = 'dropdown',
    UnlabeledUpload = 'unlabeled_upload',
    LabeledUpload = 'labeled_upload'
}

