/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAddGroupPricesInner } from '../models/ProductAddGroupPricesInner';
import { HttpFile } from '../http/http';

export class ProductVariantPriceAdd {
    /**
    * Defines the variant to which the price has to be added
    */
    'id'?: string;
    /**
    * Product id
    */
    'productId'?: string;
    /**
    * Defines variants\'s group prices
    */
    'groupPrices': Array<ProductAddGroupPricesInner>;
    /**
    * Store Id
    */
    'storeId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupPrices",
            "baseName": "group_prices",
            "type": "Array<ProductAddGroupPricesInner>",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantPriceAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
