/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductVariantAddBatchPayloadInner } from '../models/ProductVariantAddBatchPayloadInner';
import { HttpFile } from '../http/http';

export class ProductVariantAddBatch {
    'clearCache'?: boolean;
    'reindex'?: boolean;
    /**
    * Contains an array of product variants objects. The list of properties may vary depending on the specific platform.
    */
    'payload': Array<ProductVariantAddBatchPayloadInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clearCache",
            "baseName": "clear_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reindex",
            "baseName": "reindex",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<ProductVariantAddBatchPayloadInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantAddBatch.attributeTypeMap;
    }

    public constructor() {
    }
}
