/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Product } from '../models/Product';
import { HttpFile } from '../http/http';

export class ProductVariantList200ResponseResult {
    'variant'?: Array<Product>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "variant",
            "baseName": "variant",
            "type": "Array<Product>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantList200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
