/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductUpdateBatchPayloadInnerAdvancedPricesInner } from '../models/ProductUpdateBatchPayloadInnerAdvancedPricesInner';
import { ProductUpdateBatchPayloadInnerImagesInner } from '../models/ProductUpdateBatchPayloadInnerImagesInner';
import { HttpFile } from '../http/http';

export class ProductUpdateBatchPayloadInner {
    'id': string;
    'name'?: string;
    'description'?: string;
    'shortDescription'?: string;
    'sku'?: string;
    'model'?: string;
    'price'?: number;
    'specialPrice'?: number;
    'spriceCreate'?: string;
    'spriceExpire'?: string;
    'costPrice'?: number;
    'oldPrice'?: number;
    'fixedCostShippingPrice'?: number;
    /**
    * If an empty array is passed, all entries will be deleted when the \'nested_items_update_behaviour\' parameter is set to \'replace\'.
    */
    'advancedPrices'?: Array<ProductUpdateBatchPayloadInnerAdvancedPricesInner>;
    'quantity'?: number;
    'increaseQuantity'?: number;
    'reduceQuantity'?: number;
    'reserveQuantity'?: number;
    'storeId'?: string;
    'langId'?: string;
    'status'?: string;
    'type'?: string;
    'condition'?: string;
    'visible'?: string;
    'availableForView'?: boolean;
    'availableForSale'?: boolean;
    'availFrom'?: string;
    'weight'?: number;
    'length'?: number;
    'width'?: number;
    'height'?: number;
    'dimensionsUnit'?: string;
    'weightUnit'?: string;
    'manageStock'?: boolean;
    'inStock'?: boolean;
    'backorderStatus'?: string;
    'isFreeShipping'?: boolean;
    'isVirtual'?: boolean;
    'taxable'?: boolean;
    'downloadable'?: boolean;
    'warehouseId'?: string;
    'taxClassId'?: string;
    'categoriesIds'?: Array<string>;
    'metaTitle'?: string;
    'metaDescription'?: string;
    'metaKeywords'?: Array<string>;
    'url'?: string;
    'seoUrl'?: string;
    'manufacturer'?: string;
    'manufacturerId'?: string;
    'mpn'?: string;
    'gtin'?: string;
    'upc'?: string;
    'isbn'?: string;
    'ean'?: string;
    'barcode'?: string;
    /**
    * Property \'nested_items_update_behaviour\' does not apply. Specified items will be added to existing product images
    */
    'images'?: Array<ProductUpdateBatchPayloadInnerImagesInner>;
    /**
    * If an empty array is passed, all entries will be deleted when the \'nested_items_update_behaviour\' parameter is set to \'replace\'.
    */
    'relatedProductsIds'?: Array<string>;
    /**
    * If an empty array is passed, all entries will be deleted when the \'nested_items_update_behaviour\' parameter is set to \'replace\'.
    */
    'upSellProductsIds'?: Array<string>;
    /**
    * If an empty array is passed, all entries will be deleted when the \'nested_items_update_behaviour\' parameter is set to \'replace\'.
    */
    'crossSellProductsIds'?: Array<string>;
    'tags'?: Array<string>;
    'searchKeywords'?: Array<string>;
    'harmonizedSystemCode'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "specialPrice",
            "baseName": "special_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "spriceCreate",
            "baseName": "sprice_create",
            "type": "string",
            "format": ""
        },
        {
            "name": "spriceExpire",
            "baseName": "sprice_expire",
            "type": "string",
            "format": ""
        },
        {
            "name": "costPrice",
            "baseName": "cost_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "oldPrice",
            "baseName": "old_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "fixedCostShippingPrice",
            "baseName": "fixed_cost_shipping_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "advancedPrices",
            "baseName": "advanced_prices",
            "type": "Array<ProductUpdateBatchPayloadInnerAdvancedPricesInner>",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "increaseQuantity",
            "baseName": "increase_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "reduceQuantity",
            "baseName": "reduce_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "reserveQuantity",
            "baseName": "reserve_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "langId",
            "baseName": "lang_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "string",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "string",
            "format": ""
        },
        {
            "name": "availableForView",
            "baseName": "available_for_view",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availableForSale",
            "baseName": "available_for_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availFrom",
            "baseName": "avail_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "dimensionsUnit",
            "baseName": "dimensions_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "manageStock",
            "baseName": "manage_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inStock",
            "baseName": "in_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "backorderStatus",
            "baseName": "backorder_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "isFreeShipping",
            "baseName": "is_free_shipping",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taxable",
            "baseName": "taxable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "downloadable",
            "baseName": "downloadable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxClassId",
            "baseName": "tax_class_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoriesIds",
            "baseName": "categories_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "metaTitle",
            "baseName": "meta_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaDescription",
            "baseName": "meta_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaKeywords",
            "baseName": "meta_keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "seoUrl",
            "baseName": "seo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturerId",
            "baseName": "manufacturer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mpn",
            "baseName": "mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "gtin",
            "baseName": "gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "ean",
            "baseName": "ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductUpdateBatchPayloadInnerImagesInner>",
            "format": ""
        },
        {
            "name": "relatedProductsIds",
            "baseName": "related_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "upSellProductsIds",
            "baseName": "up_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "crossSellProductsIds",
            "baseName": "cross_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "searchKeywords",
            "baseName": "search_keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "harmonizedSystemCode",
            "baseName": "harmonized_system_code",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductUpdateBatchPayloadInner.attributeTypeMap;
    }

    public constructor() {
    }
}
