/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductImageAdd {
    /**
    * Defines product id where the image should be added
    */
    'productId'?: string;
    /**
    * Defines image\'s name
    */
    'imageName': string;
    /**
    * Defines image\'s types that are specified by comma-separated list
    */
    'type': ProductImageAddTypeEnum;
    /**
    * Defines URL of the image that has to be added
    */
    'url'?: string;
    /**
    * Defines alternative text that has to be attached to the picture
    */
    'label'?: string;
    /**
    * Mime type of image http://en.wikipedia.org/wiki/Internet_media_type.
    */
    'mime'?: string;
    /**
    * Defines image’s position in the list
    */
    'position'?: number;
    /**
    * Content(body) encoded in base64 of image file
    */
    'content'?: string;
    /**
    * Defines product\'s variants specified by variant id
    */
    'productVariantId'?: string;
    /**
    * Defines product\'s variants ids
    */
    'variantIds'?: string;
    /**
    * Defines product\'s option values ids
    */
    'optionValueIds'?: string;
    /**
    * Store Id
    */
    'storeId'?: string;
    /**
    * Add product image on specified language id
    */
    'langId'?: string;
    /**
    * Use the latest platform API version
    */
    'useLatestApiVersion'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageName",
            "baseName": "image_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductImageAddTypeEnum",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string",
            "format": ""
        },
        {
            "name": "mime",
            "baseName": "mime",
            "type": "string",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "productVariantId",
            "baseName": "product_variant_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "variantIds",
            "baseName": "variant_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "optionValueIds",
            "baseName": "option_value_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "langId",
            "baseName": "lang_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "useLatestApiVersion",
            "baseName": "use_latest_api_version",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductImageAdd.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductImageAddTypeEnum {
    Small = 'small',
    Base = 'base',
    Additional = 'additional',
    Thumbnail = 'thumbnail'
}

