/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAddBatchPayloadInnerAdvancedPricesInner } from '../models/ProductAddBatchPayloadInnerAdvancedPricesInner';
import { ProductAddBatchPayloadInnerImagesInner } from '../models/ProductAddBatchPayloadInnerImagesInner';
import { ProductAddFilesInner } from '../models/ProductAddFilesInner';
import { HttpFile } from '../http/http';

export class ProductAddBatchPayloadInner {
    'name'?: string;
    'description'?: string;
    'shortDescription'?: string;
    'sku'?: string;
    'model'?: string;
    'asin'?: string;
    'upc'?: string;
    'ean'?: string;
    'gtin'?: string;
    'mpn'?: string;
    'barcode'?: string;
    'price'?: number;
    'oldPrice'?: number;
    'costPrice'?: number;
    'specialPrice'?: number;
    'spriceCreate'?: string;
    'spriceExpire'?: string;
    'advancedPrices'?: Array<ProductAddBatchPayloadInnerAdvancedPricesInner>;
    'fixedCostShippingPrice'?: number;
    'quantity'?: number;
    'manageStock'?: boolean;
    'productType'?: string;
    'marketplaceItemProperties'?: any;
    'isFreeShipping'?: boolean;
    'taxable'?: boolean;
    'status'?: string;
    'condition'?: string;
    'visible'?: string;
    'availableForView'?: boolean;
    'availableForSale'?: boolean;
    'isVirtual'?: boolean;
    'inStock'?: boolean;
    'type'?: string;
    'downloadable'?: boolean;
    'weight'?: number;
    'length'?: number;
    'width'?: number;
    'height'?: number;
    'weightUnit'?: string;
    'dimensionsUnit'?: string;
    'storeId'?: string;
    'langId'?: string;
    'categoryId'?: string;
    'warehouseId'?: string;
    'categoriesIds'?: Array<string>;
    'relatedProductsIds'?: Array<string>;
    'upSellProductsIds'?: Array<string>;
    'crossSellProductsIds'?: Array<string>;
    'storesIds'?: Array<string>;
    'taxClassId'?: string;
    'metaTitle'?: string;
    'metaDescription'?: string;
    'metaKeywords'?: Array<string>;
    'searchKeywords'?: Array<string>;
    'harmonizedSystemCode'?: string;
    'url'?: string;
    'seoUrl'?: string;
    'manufacturer'?: string;
    'manufacturerId'?: string;
    'backorderStatus'?: string;
    'images'?: Array<ProductAddBatchPayloadInnerImagesInner>;
    'tags'?: Array<string>;
    'files'?: Array<ProductAddFilesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "asin",
            "baseName": "asin",
            "type": "string",
            "format": ""
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "ean",
            "baseName": "ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "gtin",
            "baseName": "gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "mpn",
            "baseName": "mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "oldPrice",
            "baseName": "old_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "costPrice",
            "baseName": "cost_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "specialPrice",
            "baseName": "special_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "spriceCreate",
            "baseName": "sprice_create",
            "type": "string",
            "format": ""
        },
        {
            "name": "spriceExpire",
            "baseName": "sprice_expire",
            "type": "string",
            "format": ""
        },
        {
            "name": "advancedPrices",
            "baseName": "advanced_prices",
            "type": "Array<ProductAddBatchPayloadInnerAdvancedPricesInner>",
            "format": ""
        },
        {
            "name": "fixedCostShippingPrice",
            "baseName": "fixed_cost_shipping_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "manageStock",
            "baseName": "manage_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "productType",
            "baseName": "product_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "marketplaceItemProperties",
            "baseName": "marketplace_item_properties",
            "type": "any",
            "format": ""
        },
        {
            "name": "isFreeShipping",
            "baseName": "is_free_shipping",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taxable",
            "baseName": "taxable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "condition",
            "baseName": "condition",
            "type": "string",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "string",
            "format": ""
        },
        {
            "name": "availableForView",
            "baseName": "available_for_view",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availableForSale",
            "baseName": "available_for_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "inStock",
            "baseName": "in_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "downloadable",
            "baseName": "downloadable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "dimensionsUnit",
            "baseName": "dimensions_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "langId",
            "baseName": "lang_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoriesIds",
            "baseName": "categories_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "relatedProductsIds",
            "baseName": "related_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "upSellProductsIds",
            "baseName": "up_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "crossSellProductsIds",
            "baseName": "cross_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "storesIds",
            "baseName": "stores_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "taxClassId",
            "baseName": "tax_class_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaTitle",
            "baseName": "meta_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaDescription",
            "baseName": "meta_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaKeywords",
            "baseName": "meta_keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "searchKeywords",
            "baseName": "search_keywords",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "harmonizedSystemCode",
            "baseName": "harmonized_system_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "seoUrl",
            "baseName": "seo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturerId",
            "baseName": "manufacturer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "backorderStatus",
            "baseName": "backorder_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductAddBatchPayloadInnerImagesInner>",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<ProductAddFilesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddBatchPayloadInner.attributeTypeMap;
    }

    public constructor() {
    }
}
