/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductUpdateBatchPayloadInner } from '../models/ProductUpdateBatchPayloadInner';
import { HttpFile } from '../http/http';

export class ProductUpdateBatch {
    /**
    *  Determines how updates to nested items should be handled.<hr><div style=\"font-style:normal\">  Values description:  <div style=\"margin-left: 2%; padding-top: 2%\">    <div style=\"font-size:85%\">      <b>  replace</b>: This option indicates that the nested items should be completely replaced with the new data provided. </br>      <b>  merge</b>: With this option, updates to nested items are merged with the existing data. </br>    </div>  </div></div>
    */
    'nestedItemsUpdateBehaviour'?: ProductUpdateBatchNestedItemsUpdateBehaviourEnum;
    'clearCache'?: boolean;
    'reindex'?: boolean;
    /**
    * Contains an array of product objects. The list of properties may vary depending on the specific platform.
    */
    'payload': Array<ProductUpdateBatchPayloadInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nestedItemsUpdateBehaviour",
            "baseName": "nested_items_update_behaviour",
            "type": "ProductUpdateBatchNestedItemsUpdateBehaviourEnum",
            "format": ""
        },
        {
            "name": "clearCache",
            "baseName": "clear_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reindex",
            "baseName": "reindex",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<ProductUpdateBatchPayloadInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductUpdateBatch.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductUpdateBatchNestedItemsUpdateBehaviourEnum {
    Replace = 'replace',
    Merge = 'merge'
}

