/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductDeleteBatchPayloadInner } from '../models/ProductDeleteBatchPayloadInner';
import { HttpFile } from '../http/http';

export class ProductDeleteBatch {
    /**
    * Contains an array of product deletion requests, each including the product ID.
    */
    'payload': Array<ProductDeleteBatchPayloadInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payload",
            "baseName": "payload",
            "type": "Array<ProductDeleteBatchPayloadInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductDeleteBatch.attributeTypeMap;
    }

    public constructor() {
    }
}
