/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Manufacturer information.
*/
export class ProductAddManufacturerInfo {
    /**
    * Defines manufacturer`s name
    */
    'name'?: string;
    /**
    * Defines manufacturer`s address
    */
    'address'?: string;
    /**
    * Defines manufacturer`s phone
    */
    'phone'?: string;
    /**
    * Defines manufacturer`s email
    */
    'email'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddManufacturerInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
