/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* If the seller is subscribed to \"Business Policies\", use the seller_profiles instead of the shipping_details, payment_methods and return_accepted params.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">seller_profiles[<b>shipping_profile_id</b>] = string</br>seller_profiles[<b>payment_profile_id</b>] = string</br>seller_profiles[<b>return_profile_id</b>] = string</br></code></div></div>
*/
export class ProductAddSellerProfiles {
    'shippingProfileId'?: string;
    'paymentProfileId'?: string;
    'returnProfileId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shippingProfileId",
            "baseName": "shipping_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentProfileId",
            "baseName": "payment_profile_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "returnProfileId",
            "baseName": "return_profile_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddSellerProfiles.attributeTypeMap;
    }

    public constructor() {
    }
}
