/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { HttpFile } from '../http/http';

export class ProductAdvancedPrice {
    'id'?: string;
    'value'?: number;
    'avail'?: boolean;
    'groupId'?: string;
    'quantityFrom'?: number;
    'startTime'?: A2CDateTime;
    'expireTime'?: A2CDateTime;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "avail",
            "baseName": "avail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantityFrom",
            "baseName": "quantity_from",
            "type": "number",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "expireTime",
            "baseName": "expire_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAdvancedPrice.attributeTypeMap;
    }

    public constructor() {
    }
}
