/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductVariantAddBatchPayloadInnerCombinationInner {
    'optionName': string;
    'optionValueName': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "optionName",
            "baseName": "option_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "optionValueName",
            "baseName": "option_value_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantAddBatchPayloadInnerCombinationInner.attributeTypeMap;
    }

    public constructor() {
    }
}
