/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAddTierPricesInner } from '../models/ProductAddTierPricesInner';
import { ProductVariantAddAttributesInner } from '../models/ProductVariantAddAttributesInner';
import { HttpFile } from '../http/http';

export class ProductVariantAdd {
    /**
    * Defines product\'s id where the variant has to be added
    */
    'productId'?: string;
    /**
    * Defines variant\'s name that has to be added
    */
    'name'?: string;
    /**
    * Specifies variant\'s model that has to be added
    */
    'model': string;
    /**
    * Defines variant\'s sku that has to be added
    */
    'sku'?: string;
    /**
    * A barcode is a unique code composed of numbers used as a product identifier.
    */
    'barcode'?: string;
    /**
    * Global Trade Item Number. An GTIN is an identifier for trade items.
    */
    'gtin'?: string;
    /**
    * Defines new product\'s variant price
    */
    'price'?: number;
    /**
    * Defines product\'s old price
    */
    'oldPrice'?: number;
    /**
    * Defines new product\'s cost price
    */
    'costPrice'?: number;
    /**
    * Specifies fixed cost shipping price
    */
    'fixedCostShippingPrice'?: number;
    /**
    * Defines variant\'s attributes list
    */
    'attributes'?: Array<ProductVariantAddAttributesInner>;
    /**
    * Specifies variant\'s description
    */
    'description'?: string;
    /**
    * Specifies variant\'s model that has to be added
    */
    'specialPrice'?: number;
    /**
    * Defines the date of special price creation
    */
    'spriceCreate'?: string;
    /**
    * Defines the date of special price modification
    */
    'spriceModified'?: string;
    /**
    * Defines the term of special price offer duration
    */
    'spriceExpire'?: string;
    /**
    * Specifies the set of visible/invisible product\'s variants for users
    */
    'availableForView'?: boolean;
    /**
    * Specifies the set of visible/invisible product\'s variants for sale
    */
    'availableForSale'?: boolean;
    /**
    * Weight
    */
    'weight'?: number;
    /**
    * Defines product\'s width
    */
    'width'?: number;
    /**
    * Defines product\'s height
    */
    'height'?: number;
    /**
    * Defines product\'s length
    */
    'length'?: number;
    /**
    * Weight Unit
    */
    'weightUnit'?: string;
    /**
    * Defines short description
    */
    'shortDescription'?: string;
    /**
    * This parameter is used for selecting a warehouse where you need to set/modify a product quantity.
    */
    'warehouseId'?: string;
    /**
    * Defines product variant\'s quantity that has to be added
    */
    'quantity'?: number;
    /**
    * Defines the date of entity creation
    */
    'createdAt'?: string;
    /**
    * Specifies the product variant\'s manufacturer
    */
    'manufacturer'?: string;
    /**
    * Defines tax classes where entity has to be added
    */
    'taxClassId'?: string;
    /**
    * Defines unique meta title for each entity
    */
    'metaTitle'?: string;
    /**
    * Defines unique meta keywords for each entity
    */
    'metaKeywords'?: string;
    /**
    * Defines unique meta description of a entity
    */
    'metaDescription'?: string;
    /**
    * Defines unique product variant\'s URL
    */
    'url'?: string;
    /**
    * Add variants specified by store id
    */
    'storeId'?: string;
    /**
    * Language id
    */
    'langId'?: string;
    /**
    * Is cache clear required
    */
    'clearCache'?: boolean;
    /**
    * Specifies whether a tax is charged
    */
    'taxable'?: boolean;
    /**
    * Harmonized System Code. An HSC is a 6-digit identifier that allows participating countries to classify traded goods on a common basis for customs purposes
    */
    'harmonizedSystemCode'?: string;
    /**
    * The country where the inventory item was made
    */
    'countryOfOrigin'?: string;
    /**
    * Defines inventory tracking for product variant
    */
    'manageStock'?: boolean;
    /**
    * Universal Product Code. A UPC (UPC-A) is a commonly used identifer for many different products.
    */
    'upc'?: string;
    /**
    * Manufacturer Part Number. A MPN is an identifier of a particular part design or material used.
    */
    'mpn'?: string;
    /**
    * European Article Number. An EAN is a unique 8 or 13-digit identifier that many industries (such as book publishers) use to identify products.
    */
    'ean'?: string;
    /**
    * International Standard Book Number. An ISBN is a unique identifier for books.
    */
    'isbn'?: string;
    /**
    * Assign variant to the stores that is specified by comma-separated stores\' id
    */
    'storesIds'?: string;
    /**
    * Defines as a default variant
    */
    'isDefault'?: boolean;
    /**
    * Specifies variant\'s free shipping flag that has to be added
    */
    'isFreeShipping'?: boolean;
    /**
    * String containing the JSON representation of the supplied data
    */
    'marketplaceItemProperties'?: string;
    /**
    * Set stock status
    */
    'inStock'?: boolean;
    /**
    * Set backorder status
    */
    'backorderStatus'?: string;
    /**
    * Defines product\'s tier prices
    */
    'tierPrices'?: Array<ProductAddTierPricesInner>;
    /**
    * Defines whether the product is virtual
    */
    'isVirtual'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "sku",
            "baseName": "sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string",
            "format": ""
        },
        {
            "name": "gtin",
            "baseName": "gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "oldPrice",
            "baseName": "old_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "costPrice",
            "baseName": "cost_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "fixedCostShippingPrice",
            "baseName": "fixed_cost_shipping_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Array<ProductVariantAddAttributesInner>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "specialPrice",
            "baseName": "special_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "spriceCreate",
            "baseName": "sprice_create",
            "type": "string",
            "format": ""
        },
        {
            "name": "spriceModified",
            "baseName": "sprice_modified",
            "type": "string",
            "format": ""
        },
        {
            "name": "spriceExpire",
            "baseName": "sprice_expire",
            "type": "string",
            "format": ""
        },
        {
            "name": "availableForView",
            "baseName": "available_for_view",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availableForSale",
            "baseName": "available_for_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "string",
            "format": ""
        },
        {
            "name": "taxClassId",
            "baseName": "tax_class_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaTitle",
            "baseName": "meta_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaKeywords",
            "baseName": "meta_keywords",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaDescription",
            "baseName": "meta_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "storeId",
            "baseName": "store_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "langId",
            "baseName": "lang_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "clearCache",
            "baseName": "clear_cache",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "taxable",
            "baseName": "taxable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "harmonizedSystemCode",
            "baseName": "harmonized_system_code",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryOfOrigin",
            "baseName": "country_of_origin",
            "type": "string",
            "format": ""
        },
        {
            "name": "manageStock",
            "baseName": "manage_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "upc",
            "baseName": "upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "mpn",
            "baseName": "mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "ean",
            "baseName": "ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "storesIds",
            "baseName": "stores_ids",
            "type": "string",
            "format": ""
        },
        {
            "name": "isDefault",
            "baseName": "is_default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isFreeShipping",
            "baseName": "is_free_shipping",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "marketplaceItemProperties",
            "baseName": "marketplace_item_properties",
            "type": "string",
            "format": ""
        },
        {
            "name": "inStock",
            "baseName": "in_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "backorderStatus",
            "baseName": "backorder_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tierPrices",
            "baseName": "tier_prices",
            "type": "Array<ProductAddTierPricesInner>",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductVariantAdd.attributeTypeMap;
    }

    public constructor() {
    }
}
