/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductOptionValueAdd200ResponseResult {
    'optionValueId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "optionValueId",
            "baseName": "option_value_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductOptionValueAdd200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
