/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { Discount } from '../models/Discount';
import { Image } from '../models/Image';
import { ProductAdvancedPrice } from '../models/ProductAdvancedPrice';
import { ProductGroupItem } from '../models/ProductGroupItem';
import { ProductGroupPrice } from '../models/ProductGroupPrice';
import { ProductInventory } from '../models/ProductInventory';
import { ProductOption } from '../models/ProductOption';
import { ProductTierPrice } from '../models/ProductTierPrice';
import { SpecialPrice } from '../models/SpecialPrice';
import { HttpFile } from '../http/http';

export class Product {
    'id'?: string;
    'type'?: string;
    'uModel'?: string;
    'uSku'?: string;
    'name'?: string;
    'description'?: string;
    'shortDescription'?: string;
    'price'?: number;
    'advancedPrice'?: Array<ProductAdvancedPrice>;
    'costPrice'?: number;
    'quantity'?: number;
    'inventory'?: Array<ProductInventory>;
    'groupItems'?: Array<ProductGroupItem>;
    'uBrandId'?: string;
    'uBrand'?: string;
    'categoriesIds'?: Array<string>;
    'storesIds'?: Array<string>;
    'url'?: string;
    'seoUrl'?: string;
    'metaTitle'?: string;
    'metaKeywords'?: string;
    'metaDescription'?: string;
    'availSale'?: boolean;
    'availView'?: boolean;
    'isVirtual'?: boolean;
    'isDownloadable'?: boolean;
    'weight'?: number;
    'weightUnit'?: string;
    'sortOrder'?: number;
    'inStock'?: boolean;
    'onSale'?: boolean;
    'backorders'?: string;
    'manageStock'?: string;
    'isStockManaged'?: boolean;
    'createAt'?: A2CDateTime;
    'modifiedAt'?: A2CDateTime;
    'taxClassId'?: string;
    'specialPrice'?: SpecialPrice;
    'tierPrice'?: Array<ProductTierPrice>;
    'groupPrice'?: Array<ProductGroupPrice>;
    'images'?: Array<Image>;
    'productOptions'?: Array<ProductOption>;
    'uUpc'?: string;
    'uMpn'?: string;
    'uGtin'?: string;
    'uIsbn'?: string;
    'uEan'?: string;
    'relatedProductsIds'?: Array<string>;
    'upSellProductsIds'?: Array<string>;
    'crossSellProductsIds'?: Array<string>;
    'dimensionsUnit'?: string;
    'width'?: number;
    'height'?: number;
    'length'?: number;
    'discounts'?: Array<Discount>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "uModel",
            "baseName": "u_model",
            "type": "string",
            "format": ""
        },
        {
            "name": "uSku",
            "baseName": "u_sku",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortDescription",
            "baseName": "short_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "advancedPrice",
            "baseName": "advanced_price",
            "type": "Array<ProductAdvancedPrice>",
            "format": ""
        },
        {
            "name": "costPrice",
            "baseName": "cost_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<ProductInventory>",
            "format": ""
        },
        {
            "name": "groupItems",
            "baseName": "group_items",
            "type": "Array<ProductGroupItem>",
            "format": ""
        },
        {
            "name": "uBrandId",
            "baseName": "u_brand_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uBrand",
            "baseName": "u_brand",
            "type": "string",
            "format": ""
        },
        {
            "name": "categoriesIds",
            "baseName": "categories_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "storesIds",
            "baseName": "stores_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "seoUrl",
            "baseName": "seo_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaTitle",
            "baseName": "meta_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaKeywords",
            "baseName": "meta_keywords",
            "type": "string",
            "format": ""
        },
        {
            "name": "metaDescription",
            "baseName": "meta_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "availSale",
            "baseName": "avail_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availView",
            "baseName": "avail_view",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isVirtual",
            "baseName": "is_virtual",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDownloadable",
            "baseName": "is_downloadable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightUnit",
            "baseName": "weight_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortOrder",
            "baseName": "sort_order",
            "type": "number",
            "format": ""
        },
        {
            "name": "inStock",
            "baseName": "in_stock",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "onSale",
            "baseName": "on_sale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "backorders",
            "baseName": "backorders",
            "type": "string",
            "format": ""
        },
        {
            "name": "manageStock",
            "baseName": "manage_stock",
            "type": "string",
            "format": ""
        },
        {
            "name": "isStockManaged",
            "baseName": "is_stock_managed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createAt",
            "baseName": "create_at",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "modifiedAt",
            "baseName": "modified_at",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "taxClassId",
            "baseName": "tax_class_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "specialPrice",
            "baseName": "special_price",
            "type": "SpecialPrice",
            "format": ""
        },
        {
            "name": "tierPrice",
            "baseName": "tier_price",
            "type": "Array<ProductTierPrice>",
            "format": ""
        },
        {
            "name": "groupPrice",
            "baseName": "group_price",
            "type": "Array<ProductGroupPrice>",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Image>",
            "format": ""
        },
        {
            "name": "productOptions",
            "baseName": "product_options",
            "type": "Array<ProductOption>",
            "format": ""
        },
        {
            "name": "uUpc",
            "baseName": "u_upc",
            "type": "string",
            "format": ""
        },
        {
            "name": "uMpn",
            "baseName": "u_mpn",
            "type": "string",
            "format": ""
        },
        {
            "name": "uGtin",
            "baseName": "u_gtin",
            "type": "string",
            "format": ""
        },
        {
            "name": "uIsbn",
            "baseName": "u_isbn",
            "type": "string",
            "format": ""
        },
        {
            "name": "uEan",
            "baseName": "u_ean",
            "type": "string",
            "format": ""
        },
        {
            "name": "relatedProductsIds",
            "baseName": "related_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "upSellProductsIds",
            "baseName": "up_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "crossSellProductsIds",
            "baseName": "cross_sell_products_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "dimensionsUnit",
            "baseName": "dimensions_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "discounts",
            "baseName": "discounts",
            "type": "Array<Discount>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Product.attributeTypeMap;
    }

    public constructor() {
    }
}
