/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductAddCertificationsInnerFilesInner } from '../models/ProductAddCertificationsInnerFilesInner';
import { ProductAddCertificationsInnerImagesInner } from '../models/ProductAddCertificationsInnerImagesInner';
import { HttpFile } from '../http/http';

export class ProductAddCertificationsInner {
    /**
    * Certification ID
    */
    'id': string;
    /**
    * Certification images
    */
    'images'?: Array<ProductAddCertificationsInnerImagesInner>;
    /**
    * Certification files
    */
    'files'?: Array<ProductAddCertificationsInnerFilesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<ProductAddCertificationsInnerImagesInner>",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<ProductAddCertificationsInnerFilesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddCertificationsInner.attributeTypeMap;
    }

    public constructor() {
    }
}
