/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* If the seller is subscribed to \"Business Policies\", use the seller_profiles instead of the shipping_details, payment_methods and return_accepted params.<hr><div style=\"font-style:normal\">Param structure:<div style=\"margin-left: 2%;\"><code style=\"padding:0; background-color:#ffffff;font-size:85%;font-family:monospace;\">package_details[<b>measure_unit</b>] = string</br> Allowed measure_unit values: [English or Metric] </br> Default: Metric</br>package_details[<b>weigh_unit</b>] = string</br> Allowed weigh_unit values: [kg, g, lbs, oz]</br>package_details[<b>package_depth</b>] = decimal</br>package_details[<b>package_length</b>] = decimal</br>package_details[<b>package_width</b>] = decimal</br>package_details[<b>weight_major</b>] = decimal</br>package_details[<b>weight_minor</b>] = decimal</br>package_details[<b>shipping_package</b>] = string</br> See cart.info method, param `eBay_shipping_package_details`</code></div></div>
*/
export class ProductAddPackageDetails {
    'measureUnit'?: string;
    'weighUnit'?: string;
    'packageDepth'?: number;
    'packageLength'?: number;
    'packageWidth'?: number;
    'weightMajor'?: number;
    'weightMinor'?: number;
    'shippingPackage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "measureUnit",
            "baseName": "measure_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "weighUnit",
            "baseName": "weigh_unit",
            "type": "string",
            "format": ""
        },
        {
            "name": "packageDepth",
            "baseName": "package_depth",
            "type": "number",
            "format": ""
        },
        {
            "name": "packageLength",
            "baseName": "package_length",
            "type": "number",
            "format": ""
        },
        {
            "name": "packageWidth",
            "baseName": "package_width",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightMajor",
            "baseName": "weight_major",
            "type": "number",
            "format": ""
        },
        {
            "name": "weightMinor",
            "baseName": "weight_minor",
            "type": "number",
            "format": ""
        },
        {
            "name": "shippingPackage",
            "baseName": "shipping_package",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductAddPackageDetails.attributeTypeMap;
    }

    public constructor() {
    }
}
