/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerGroup } from '../models/CustomerGroup';
import { HttpFile } from '../http/http';

export class ResponseCustomerGroupListResult {
    'groupCount'?: number;
    'group'?: Array<CustomerGroup>;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupCount",
            "baseName": "group_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "Array<CustomerGroup>",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseCustomerGroupListResult.attributeTypeMap;
    }

    public constructor() {
    }
}
