/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { A2CDateTime } from '../models/A2CDateTime';
import { ShipmentItem } from '../models/ShipmentItem';
import { ShipmentTrackingNumber } from '../models/ShipmentTrackingNumber';
import { HttpFile } from '../http/http';

export class Shipment {
    'id'?: string;
    'orderId'?: string;
    'name'?: string;
    'warehouseId'?: string;
    'shipmentProvider'?: string;
    'trackingNumbers'?: Array<ShipmentTrackingNumber>;
    'createdAt'?: A2CDateTime;
    'modifiedTime'?: A2CDateTime;
    'items'?: Array<ShipmentItem>;
    'isShipped'?: boolean;
    'deliveredAt'?: A2CDateTime;
    'additionalFields'?: any;
    'customFields'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "warehouseId",
            "baseName": "warehouse_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentProvider",
            "baseName": "shipment_provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingNumbers",
            "baseName": "tracking_numbers",
            "type": "Array<ShipmentTrackingNumber>",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "modifiedTime",
            "baseName": "modified_time",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ShipmentItem>",
            "format": ""
        },
        {
            "name": "isShipped",
            "baseName": "is_shipped",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "deliveredAt",
            "baseName": "delivered_at",
            "type": "A2CDateTime",
            "format": ""
        },
        {
            "name": "additionalFields",
            "baseName": "additional_fields",
            "type": "any",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Shipment.attributeTypeMap;
    }

    public constructor() {
    }
}
