/**
 * API2Cart OpenAPI
 * API2Cart
 *
 * OpenAPI spec version: 1.1
 * Contact: contact@api2cart.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebhookEvents200ResponseResultEventsInner } from '../models/WebhookEvents200ResponseResultEventsInner';
import { HttpFile } from '../http/http';

export class WebhookEvents200ResponseResult {
    'events'?: Array<WebhookEvents200ResponseResultEventsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<WebhookEvents200ResponseResultEventsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebhookEvents200ResponseResult.attributeTypeMap;
    }

    public constructor() {
    }
}
